language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
before_script:
- curl http://mirrors.ibiblio.org/apache/jena/binaries/apache-jena-3.12.0.tar.gz | tar -zx -C /opt
script: TESTING=1 RIOT=/opt/apache-jena-3.12.0/bin/riot python3 -m unittest discover
