name: server tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: >-
          TESTING=1
          SKIP_TRANSLATION=true
          make test
